[package]
name = "symmetric-interaction-calculus-cli"
version = "0.1.0"
authors = ["maiavictor <srvictormaia@gmail.com>"]

[dependencies]
clap = "2.26.0"
symmetric-interaction-calculus = "0.1.3"

[[bin]]
name = "sic"
path = "src/main.rs"
